# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quadrant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marshall.Classification'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marshall.Field'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='quadrant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marshall.Quadrant'),
        ),
    ]
